### ISSUE TITLE
How to change the data structure ?

### ISSUE THREAD

**Issue by jchapuy** [geofirestore/geofirestore-js#145] opened 2019-10-24 14:11 UTC
Is it possible to change the data structure ?

I am using [https://pub.dev/packages/geoflutterfire](https://pub.dev/packages/geoflutterfire) to perform geo based queries in a flutter application, and this package uses another data structure (as show in the screenshot below)

![Capture d’écran 2019-10-24 à 16 02 07](https://user-images.githubusercontent.com/10288029/67493448-2a6ff700-f678-11e9-8f6b-91f5988818bd.png)

I am calling geofirestore-js using `<script src="https://unpkg.com/geofirestore/dist/geofirestore.js"></script>` on a Wordpress website.

I would like to have a standardized database that can be called from geofirestore-js and geoflutterfire, and this is why I would like to change the data structure of geofirestore-js to match the one I am already using on my app.

How can I accomplish that ?

Thanks for your amazing work !

**Comment by MichaelSolati** [comment] 2019-11-24 16:52
This library will likely not follow the same model as "geoflutterfire" as it was originally a fork of geofire, so it follows it's design. However as a dupe of #103 you'll see geofirestore using a more flexible data structure.

**Closed by MichaelSolati** 2019-11-24 16:52 UTC
