### ISSUE TITLE
Slow Performance on 360k Records - Running as Node.js function

### ISSUE THREAD

**Issue by stevenyix** [geofirestore/geofirestore-js#55] opened 2018-12-14 21:12 UTC
I'm using geofirestore in a firestore cloud function with an http endpoint to perform radius search - return records within the radius of a lat/lon coordinate.

This query runs against a document collection with 360k records.

The performance is quite slow - queries are taking 12-14 seconds according to the Cloud Functions log.  In comparison, I created a small Cloud SQL Postgres database and Express.js web API and it’s returning identical queries in 300ms.

I have one composite index created, otherwise it’s using default setting.  The composite index I created is:  "d.locationType ASC g ASC".

Below is a screenshot of the document structure.  I added a few child fields in the 'd' field created by Geofirestore.

I posted this question on the google-cloud-firestore-discuss@googlegroups.com discussion group, and one of the Firestore engineers suggested reaching out to you - but would be willing to talk with the geofirestore developers and possibly help.  I'll point him to this issue.

Any guidance on how to optimize this to run - ideally <1 sec?

![image](https://user-images.githubusercontent.com/7738085/50027603-a0f49080-ffa1-11e8-879f-6a5280869843.png)

**Comment by samtstern** [comment] 2018-12-14 21:34
cc'ing myself here: curious to know how this library works and if there are possible optimizations!

**Comment by alexandregiordanelli** [comment] 2018-12-30 18:31
https://github.com/geofirestore/geofirestore-js/issues/63

The problem is that library is downloading 360k record and filter after on clientside..

**Comment by MichaelSolati** [comment] 2018-12-30 20:44
@alexandregiordanelli the library does not in fact download the entire 360k record. It does an initial filter based on geohashes via firestores startat and endat functions and then does another check on client in case the document is off a little (as is the nature with geohashes)

**Comment by MichaelSolati** [comment] 2018-12-31 05:55
@stevenyix closing this as it's been almost two weeks since I last heard any update from you, please feel free to comment back if my solution didn't work for you.

**Closed by MichaelSolati** 2018-12-31 05:55 UTC
Labels: question
